version: 2.1

jobs:
  build:
    docker:
      - image: bdls/django_lettings:8ae1d8a37777deb6f4264473894eca4144df4916
    steps:
      - checkout
      - run:
          command: |
            python -m venv .venv
            source .venv/bin/activate
            pip install -r requirements.txt
  test:
    docker:
      - image: bdls/django_lettings:8ae1d8a37777deb6f4264473894eca4144df4916
    steps:
      - checkout
      - run:
          command: pytest

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
