version: 2.1

jobs:
  build_test:
    docker:
      - image: python:3.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv .venv
            source .venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            source .venv/bin/activate
            pytest

  containerize:
    docker:
      - image: docker:latest
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build Docker image
          command: |
            echo $CIRCLE_SHA1
            docker build --build-arg COMMIT_SHA=$CIRCLE_SHA1 -t oc_lettings:$CIRCLE_SHA1 .
      - run:
          name: Run Docker image
          command: docker run -d -p 8000:8000 oc_lettings:$CIRCLE_SHA1
      - run:
          name: Push Docker image to DockerHub
          command: |
            docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASSWORD
            docker tag oc_lettings:$CIRCLE_SHA1 $DOCKERHUB_USERNAME/oc_lettings:$CIRCLE_SHA1
            docker push $DOCKERHUB_USERNAME/oc_lettings:$CIRCLE_SHA1

  deploy:
    docker:
      - image: cimg/python:3.10
    environment:
      - HEROKU_APP_NAME: oc-python-projet-13
    steps:
      - checkout
      - run:
          name: Install Heroku CLI
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
      - setup_remote_docker

      - run:
          name: Check if Heroku app exists
          id: oc-python-projet-13
          command: |
            set -e
            if heroku apps:info --app oc-python-projet-13 >/dev/null 2>&1; then
              echo "::set-output name=app_exists::true"
            else
              echo "::set-output name=app_exists::false"
            fi

      - run: 
          name: Create Heroku app if it doesn't exist
          command: |
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login
            heroku apps:info -a oc-python-projet-13 || heroku create oc-python-projet-13
            

      - run: 
          name: Deploy to Heroku
          command: |
            docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASSWORD
            echo "OK 1"
            docker image pull $DOCKERHUB_USERNAME/oc_lettings:$CIRCLE_SHA1
            echo "OK 2"
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login
            echo "OK 3"
            docker tag $DOCKERHUB_USERNAME/oc_lettings:$CIRCLE_SHA1 registry.heroku.com/$HEROKU_APP_NAME/web
            echo "OK 4"
            docker push registry.heroku.com/$HEROKU_APP_NAME/web
            echo "OK 5"
            heroku container:release web --app $HEROKU_APP_NAME
            echo "OK 6"

workflows:
  build_test_deploy:
    jobs:
      - build_test
      - containerize:
          requires:
            - build_test
      - deploy:
          requires:
            - containerize
