version: 2.1

jobs:
  build_test:
    docker:
      - image: python:3.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv .venv
            source .venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            source .venv/bin/activate
            pytest

  containerize:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: |
            docker build \
              --build-arg COMMIT_SHA=$(echo $CIRCLE_SHA1 | cut -c 1-7) \
              -t oc_lettings:$CIRCLE_SHA1 .
      - run:
          name: Run Docker image
          command: docker run -d -p 8000:8000 oc_lettings:$CIRCLE_SHA1
      - run:
          name: Push Docker image to DockerHub
          command: |
            docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASSWORD
            docker tag oc_lettings:$CIRCLE_SHA1 $DOCKERHUB_USERNAME/oc_lettings:$CIRCLE_SHA1
            docker push $DOCKERHUB_USERNAME/oc_lettings:$CIRCLE_SHA1

  deploy:
    docker:
        - image: oc_lettings:$CIRCLE_SHA1
    environment:
      - HEROKU_APP_NAME: oc-python-projet-13
      - HEROKU_API_KEY: $HEROKU_API_KEY
      - HEROKU_USERNAME: $HEROKU_USERNAME
    steps:
      - run:
          name: Deploy to Heroku
          command: |
            docker login --username=$HEROKU_USERNAME --password=$HEROKU_API_KEY registry.heroku.com
            docker tag oc_lettings:$CIRCLE_SHA1 registry.heroku.com/$HEROKU_APP_NAME/web
            docker push registry.heroku.com/$HEROKU_APP_NAME/web
            heroku container:release web --app $HEROKU_APP_NAME

workflows:
  build_test_deploy:
    jobs:
      - build_test
      - containerize:
          requires:
            - build_test
      - deploy:
          requires:
            - containerize
